# Generated by Django 4.0.3 on 2022-08-16 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Budget Name')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Sum')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_with', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Record Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('category', models.CharField(default='uncategorized', max_length=30, verbose_name='Category')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget')),
            ],
        ),
    ]
