version: "3.7"

services:
    family_budget_db:
        image: postgres:13.6
        environment:
            POSTGRES_PASSWORD: "admin123"
            POSTGRES_USER: "admin321"
            POSTGRES_DB: "family_budget"
        ports:
            - "5432:5432"
    family_budget_backend:
        image: fb_backend
        build: .
        command: ${DOCKER_CMD}
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - family_budget_db
